### ISSUE TITLE
[] syntax in Lists

### ISSUE THREAD

**Issue by new-user-name** [system-f/fp-course#392]
Does
https://github.com/system-f/fp-course/blob/6741d30311428463ce1202c9d4c20881732c2d94/src/Course/List.hs#L126
have to return [1,2,3] syntax really?.. I have something like
`*Main> 11 :. (12 :. (13 :. Nil))`
No wonder, we have our custom List, not native.

**Comment by tonymorris** [comment]
It will output this syntax due to the `Show` instance being implemented the way it is.

**Comment by new-user-name** [comment]
Oops. My fault. Sorry.
