### ISSUE TITLE
JsonParser suggests use of System.IO.readFile instead of readFile defined in List.hs

### ISSUE THREAD

**Issue by michaelwebb76** [system-f/fp-course#416]
I'm sure I could get it to work with System.IO.readFile with a bit of fiddling but it seemed inconsistent with previous exercises?

Suggestion made at:
https://github.com/system-f/fp-course/blob/master/src/Course/JsonParser.hs#L258

readFile method that already works with internal `Chars` type defined at:
https://github.com/system-f/fp-course/blob/master/src/Course/List.hs#L366

**Comment by tonymorris** [comment]
Cheers. It's actually easier to solve using the internal function.

**Comment by michaelwebb76** [comment]
Thanks Tony
